version: '3.4'
services:
  pg_database:
    image: ${POSTGRES_IMAGE}
    network_mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=minio_logs
    volumes:
      - database:${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  log_search:
    image: ${LOGSEARCH_IMAGE}
    network_mode: host
    environment:
      - LOGSEARCH_AUDIT_AUTH_TOKEN=${LOGSEARCH_AUDIT_AUTH_TOKEN}
      - LOGSEARCH_QUERY_AUTH_TOKEN=${LOGSEARCH_QUERY_AUTH_TOKEN}
      - LOGSEARCH_DISK_CAPACITY_GB=${LOGSEARCH_DISK_CAPACITY_GB}
      - LOGSEARCH_MAX_RETENTION_MONTHS=${LOGSEARCH_MAX_RETENTION_MONTHS}
      - LOGSEARCH_PG_CONN_STR=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/minio_logs?sslmode=disable
    ports:
      - ${LOGSEARCH_PORT}:${LOGSEARCH_PORT}
    command: ["/usr/bin/wait-for-it.sh", "localhost:${POSTGRES_PORT}", "--", "/logsearchapi"]
    volumes:
      - ./wait-for-it.sh:/usr/bin/wait-for-it.sh
    depends_on:
      - pg_database

  console:
    image: ${CONSOLE_IMAGE}
    network_mode: host
    environment:
      - CONSOLE_PBKDF_PASSPHRASE=${CONSOLE_PBKDF_PASSPHRASE}
      - CONSOLE_PBKDF_SALT=${CONSOLE_PBKDF_SALT}
      - LOGSEARCH_QUERY_AUTH_TOKEN=${LOGSEARCH_QUERY_AUTH_TOKEN}
      - CONSOLE_MINIO_SERVER=${CONSOLE_MINIO_SERVER}
      - CONSOLE_LOG_QUERY_URL=http://localhost:${LOGSEARCH_PORT}
      - CONSOLE_PROMETHEUS_URL=http://localhost:${PROMETHEUS_PORT}
    ports:
      - "9090:9090"
    command: server
    depends_on:
      - log_search
      - prometheus

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    network_mode: host
    ports:
      - ${PROMETHEUS_PORT}:${PROMETHEUS_PORT}
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.listen-address=:${PROMETHEUS_PORT}
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  database:
